name: Java CI with Maven

on:
  push:
    branches: [ main, master, bfs, dfs ]
  pull_request:
    branches: [ main, master, bfs, dfs ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      working-directory: "Project Part 1 + 2"
      run: mvn -B package
    
    - name: Test with Maven
      working-directory: "Project Part 1 + 2"
      run: mvn test